Update to zarith 1.2.1

diff --git a/zarith/configure b/zarith/configure
--- a/zarith/configure
+++ b/zarith/configure
@@ -44,6 +44,8 @@ ccdef=''
 mlflags="$OCAMLFLAGS"
 mloptflags="$OCAMLOPTFLAGS"
 mlinc="$OCAMLINC"
+objsuffix="o"
+ocamlfind="auto"
 
 # sanitize
 LC_ALL=C
@@ -86,8 +88,11 @@ while : ; do
         -installdir|--installdir)
             installdir="$2"
             shift;;
-        -ocamllibdir|---ocamllibdir)
+        -ocamllibdir|--ocamllibdir)
             ocamllibdir="$2"
+            shift;;
+        -no-ocamlfind|--no-ocamlfind)
+            ocamlfind="no"
             shift;;
         -host|--host)
             host="$2"
@@ -120,6 +125,7 @@ echo_n()
 
 searchbin()
 {
+    if test "x$1" = "x"; then return 0; fi
     echo_n "binary $1: "
     IFS=':'
     for i in $PATH
@@ -181,12 +187,21 @@ checkcc()
     return $r
 }
 
+checkcmxalib()
+{
+    echo_n "library $1: "
+    $ocamlopt $mloptflags $1 -o tmp.out >/dev/null 2>/dev/null || r=0
+    if test ! -x tmp.out; then r=0; fi
+    rm -f tmp.out
+    if test $r -eq 0; then echo "not found"; else echo "found"; fi
+    return $r    
+}
+
 
 # check required programs
 
 searchbinreq $ocaml
 searchbinreq $ocamlc
-searchbinreq $ocamlopt
 searchbinreq $ocamldep
 searchbinreq $ocamlmklib
 searchbinreq $ocamldoc
@@ -195,12 +210,20 @@ searchbinreq $ar
 searchbinreq perl
 
 
+# optional native-code generation
+
+hasocamlopt='no'
+
+searchbin $ocamlopt
+if test $? -eq 1; then hasocamlopt='yes'; fi
+
+
 # check C compiler
 
 checkcc
 if test $? -eq 0; then
-    # try again with no options
-    ccopt=''
+    # try again with (almost) no options
+    ccopt='-O'
     checkcc
     if test $? -eq 0; then echo "cannot compile and link program"; exit 2; fi
 fi
@@ -218,10 +241,21 @@ checkinc "caml/mlvalues.h"
 if test $? -eq 0; then echo "cannot include caml/mlvalues.h"; exit 2; fi
 
 
+# optional dynamic linking
+
+hasdynlink='no'
+
+if test $hasocamlopt = yes
+then
+    checkcmxalib dynlink.cmxa
+    if test $? -eq 1; then hasdynlink='yes'; fi
+fi
+
+
 # installation method
 
 searchbin ocamlfind
-if test $? -eq 1; then 
+if test $? -eq 1 -a $ocamlfind != "no"; then 
     instmeth='findlib'
     if test "$installdir" = "auto"
     then installdir=`ocamlfind printconf destdir`; fi
@@ -255,11 +289,11 @@ fi
 
 arch='none'
 case $host in
-    x86_64-*linux-gnu)
-        ccdef="-DZ_ELF $ccdef"
+    x86_64-*linux-gnu|x86_64-kfreebsd-gnu)
+        ccdef="-DZ_ELF -DZ_DOT_LABEL_PREFIX $ccdef"
         arch='x86_64';;
-    i686-*linux-gnu)
-        ccdef="-DZ_ELF $ccdef"
+    i486-*linux-gnu|i686-*linux-gnu|i486-kfreebsd-gnu)
+        ccdef="-DZ_ELF -DZ_DOT_LABEL_PREFIX $ccdef"
         arch='i686';;
     i686-*cygwin)
         if test "x$wordsize" = "x64"; then
@@ -270,7 +304,7 @@ case $host in
             arch='i686'
         fi
 	;;
-    i686-*darwin* | x86_64-*darwin*)
+    i386-*darwin* | x86_64-*darwin*)
         ccdef="-DZ_UNDERSCORE_PREFIX -DZ_MACOS $ccdef"
         if test "x$wordsize" = "x64"; then
             ccopt="-arch x86_64 $ccopt"
@@ -283,6 +317,9 @@ case $host in
             arch='i686'
             checkcc
         fi
+        ;;
+    armv7*-gnueabi)
+        arch='arm'
         ;;
     none)
         ;;
@@ -324,22 +361,31 @@ if test "$gmp" != 'OK'; then echo "cannot find GMP nor MPIR"; exit 2; fi
 
 # OCaml version
 
-case `ocamlc -version` in
-    3.10* | 3.11* | 3.12.0*)
-        ;;
-    3.12.* | 3.1*)
-        echo "extended comparison found!"
-        ccdef="-DZ_OCAML_COMPARE_EXT $ccdef"
+ocamlver=`ocamlc -version`
+
+# Extended comparisons available since 3.12.1
+case "$ocamlver" in
+    [12].* | 3.0* | 3.10* | 3.11* | 3.12.0*)
         ;;
     *)
+        echo "OCaml extended comparison supported"
+        ccdef="-DZ_OCAML_COMPARE_EXT $ccdef"
         ;;
 esac
 
-
+# New hash functions available since 4.00.0
+case "$ocamlver" in
+    [123].*)
+        ;;
+    *)
+        echo "OCaml new hash functions available"
+        ccdef="-DZ_OCAML_HASH $ccdef"
+        ;;
+esac
 
 # dump Makefile
 
-cat > Makefile.orig <<EOF
+cat > Makefile <<EOF
 # generated by ./configure
 
 CC=$cc
@@ -360,6 +406,9 @@ AR=$ar
 INSTALL=install
 OCAMLFIND=ocamlfind
 INSTMETH=$instmeth
+OBJSUFFIX=$objsuffix
+HASOCAMLOPT=$hasocamlopt
+HASDYNLINK=$hasdynlink
 
 include project.mak
 EOF
@@ -371,6 +420,8 @@ cat <<EOF
 
 detected configuration:
 
+  native-code:          $hasocamlopt
+  dynamic linking:      $hasdynlink
   asm path:             $arch
   defines:              $ccdef
   libraries:            $cclib
